name: CI
on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      COVERAGE_SINGLE: 20
      COVERAGE_TOTAL: 20

    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.10
      uses: actions/setup-python@main
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: pytester-cov
      id: pytester-cov
      uses: programmingwithalex/pytester-cov@main
      with:
        pytest-root-dir: 'src'
        pytest-tests-dir: 'test'
        cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
        cov-threshold-total: ${{ env.COVERAGE_TOTAL }}

    - name: Coverage single file fail - exit
      if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
      run: |
        echo "coverage single fail fail ${{ steps.pytester-cov.outputs.output-table }}"
        exit 1

    - name: Coverage total fail - exit
      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
      run: |
        echo "coverage total fail ${{ steps.pytester-cov.outputs.output-table }}"
        exit 1

    - name: Commit pytest coverage table
      uses: peter-evans/commit-comment@main
      with:
        body: ${{ steps.pytester-cov.outputs.output-table }}
